### ISSUE TITLE
Example usage with autofac

### ISSUE THREAD

**Issue by AlexKeySmith** [kswoll/asyncproxy#1]
This looks fantastic! A bit of a hidden gem when looking for async support for interceptors.

It would be great to see an example / extensions for autofac & interceptors so mere mortals like myself can make good use of it. :-)

**Comment by kswoll** [comment]
Hi @AlexKeySmith, thanks for the kind words. This project is actually deprecated.  I rewrote it and made it more flexible at https://github.com/kswoll/sexy-proxy

Can you elaborate on what sort of example you'd like to see?  I've never actually used autofac.

**Comment by AlexKeySmith** [comment]
Ah ha, love the new name! Shall I move the discussion over to the new project?

It's probably a good idea to add a link on the top of the readme on this project to point people over?

**Comment by kswoll** [comment]
@AlexKeySmith thanks!  And good idea, I've updated the readme.  And sure, continuing the discussion there would make sense.
